name: "ChatBubbles"
author: TheTealViper
version: "1.18.1.a.5"
api-version: 1.18
description: "ChatBubbles above players' heads"
main: me.TheTealViper.chatbubbles.ChatBubbles
softdepend: [Factions, PlaceholderAPI, HolographicDisplays, DecentHolograms, Citizens]
commands:
  chatbubble:
    description: Main command
    aliases: [cb]
  chatbubblereload:
    description: Main command
    aliases: [cbreload]
  chatbubbletoggle:
    description: Toggle sending chatbubbles
    aliases: [cbtoggle,cbt]